[package]
name = "game_of_life"
version = "0.1.0"
authors = ["thomani <nils.thoma@t-online.de>"]
edition = "2018"

[dependencies]
piston = "0.40.0"
piston2d-graphics = "0.29.0"
vecmath = "0.3.1"
pistoncore-glutin_window = "0.52.0"
piston2d-opengl_graphics = "0.58.0"
